POST  http://localhost:3000/userRegister/ HTTP/1.1
content-Type: application/json

{
    "name":"Donney",
    "email":"raptorlake@dkj.com",
    "password":"lp16scvvdav"
}
################################################### 

POST http://localhost:3000/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"MSVC_HITMAN@dkj.com",
    "password":"lp16scvvdav"
}

###################################################
GET http://localhost:3000/
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjVkOTVkNmRkMDNjYzEwODAzMGY3YzAiLCJpYXQiOjE2NTAzMTAzMDZ9.DNgSa9Ksa4q_Dyajzkk8q4oo6c2H3BFsxaMfxy3BHzA

